//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgSchool.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faktura
    {
        public Faktura()
        {
            this.PozycjeFaktury = new HashSet<PozycjeFaktury>();
        }
    
        public int fakturaID { get; set; }
        public string numerFaktury { get; set; }
        public System.DateTime dataWystawienia { get; set; }
        public System.DateTime dataWplaty { get; set; }
        public int firmaID { get; set; }
        public int rodzajPlatnosciID { get; set; }
        public System.DateTime terminPlatnosci { get; set; }
    
        public virtual RodzajPlatnosci RodzajPlatnosci { get; set; }
        public virtual ICollection<PozycjeFaktury> PozycjeFaktury { get; set; }
    }
}
