//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgSchool.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firma
    {
        public Firma()
        {
            this.Wplata = new HashSet<Wplata>();
        }
    
        public int firmaID { get; set; }
        public string nazwa { get; set; }
        public string opis { get; set; }
        public string nip { get; set; }
        public string regon { get; set; }
        public string telefon1 { get; set; }
        public string telefon2 { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string osobaKontaktowa { get; set; }
        public Nullable<int> statusID { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual ICollection<Wplata> Wplata { get; set; }
    }
}
