//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgSchool.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupa
    {
        public Grupa()
        {
            this.ListaDoGrup = new HashSet<ListaDoGrup>();
        }
    
        public int grupaID { get; set; }
        public string grupaNumer { get; set; }
        public string nazwa { get; set; }
        public string opis { get; set; }
        public Nullable<int> uczenID { get; set; }
        public int poziomID { get; set; }
        public int kursID { get; set; }
    
        public virtual Kurs Kurs { get; set; }
        public virtual Poziom Poziom { get; set; }
        public virtual Uczen Uczen { get; set; }
        public virtual ICollection<ListaDoGrup> ListaDoGrup { get; set; }
    }
}
