//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgSchool.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kurs
    {
        public Kurs()
        {
            this.Cennik = new HashSet<Cennik>();
            this.Grupa = new HashSet<Grupa>();
            this.Rozliczenie = new HashSet<Rozliczenie>();
            this.TytulWplaty = new HashSet<TytulWplaty>();
        }
    
        public int kursID { get; set; }
        public string nazwa { get; set; }
        public string opis { get; set; }
        public Nullable<int> poziomID { get; set; }
        public Nullable<int> pracownikID { get; set; }
    
        public virtual ICollection<Cennik> Cennik { get; set; }
        public virtual ICollection<Grupa> Grupa { get; set; }
        public virtual Poziom Poziom { get; set; }
        public virtual Pracownik Pracownik { get; set; }
        public virtual ICollection<Rozliczenie> Rozliczenie { get; set; }
        public virtual ICollection<TytulWplaty> TytulWplaty { get; set; }
    }
}
