//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgSchool.Model.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LgSchoolEntities : DbContext
    {
        public LgSchoolEntities()
            : base("name=LgSchoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Autor> Autor { get; set; }
        public DbSet<Bonusy> Bonusy { get; set; }
        public DbSet<Cennik> Cennik { get; set; }
        public DbSet<Dostepnosc> Dostepnosc { get; set; }
        public DbSet<Faktura> Faktura { get; set; }
        public DbSet<Firma> Firma { get; set; }
        public DbSet<Gatunek> Gatunek { get; set; }
        public DbSet<Grupa> Grupa { get; set; }
        public DbSet<KategoriaOcen> KategoriaOcen { get; set; }
        public DbSet<Kurs> Kurs { get; set; }
        public DbSet<ListaDoGrup> ListaDoGrup { get; set; }
        public DbSet<Materialy> Materialy { get; set; }
        public DbSet<Ocena> Ocena { get; set; }
        public DbSet<OcenyUcznia> OcenyUcznia { get; set; }
        public DbSet<Poziom> Poziom { get; set; }
        public DbSet<PozycjeFaktury> PozycjeFaktury { get; set; }
        public DbSet<Pracownik> Pracownik { get; set; }
        public DbSet<RodzajPlatnosci> RodzajPlatnosci { get; set; }
        public DbSet<Rozliczenie> Rozliczenie { get; set; }
        public DbSet<Stanowisko> Stanowisko { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TypyMaterialow> TypyMaterialow { get; set; }
        public DbSet<TytulWplaty> TytulWplaty { get; set; }
        public DbSet<Uczen> Uczen { get; set; }
        public DbSet<Usluga> Usluga { get; set; }
        public DbSet<Uzytkownik> Uzytkownik { get; set; }
        public DbSet<Wplata> Wplata { get; set; }
    }
}
