//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgSchool.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocena
    {
        public Ocena()
        {
            this.OcenyUcznia = new HashSet<OcenyUcznia>();
            this.Uczen = new HashSet<Uczen>();
        }
    
        public int ocenaID { get; set; }
        public string nazwa { get; set; }
        public string opis { get; set; }
        public Nullable<int> uczenID { get; set; }
    
        public virtual ICollection<OcenyUcznia> OcenyUcznia { get; set; }
        public virtual ICollection<Uczen> Uczen { get; set; }
    }
}
