//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgSchool.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OcenyUcznia
    {
        public int ocenyUczniaID { get; set; }
        public int uczenID { get; set; }
        public int ocenaID { get; set; }
    
        public virtual Ocena Ocena { get; set; }
        public virtual Uczen Uczen { get; set; }
    }
}
