//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgSchool.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PozycjeFaktury
    {
        public int pozycjeFakturyID { get; set; }
        public int fakturaID { get; set; }
        public int uslugaID { get; set; }
        public decimal cena { get; set; }
        public decimal ilosc { get; set; }
        public decimal rabat { get; set; }
    
        public virtual Faktura Faktura { get; set; }
        public virtual Usluga Usluga { get; set; }
    }
}
