//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgSchool.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownik
    {
        public Pracownik()
        {
            this.Kurs = new HashSet<Kurs>();
            this.Rozliczenie = new HashSet<Rozliczenie>();
        }
    
        public int pracownikID { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public System.DateTime dataUrodzenia { get; set; }
        public string pesel { get; set; }
        public string ulica { get; set; }
        public string numer { get; set; }
        public string kodPocztowy { get; set; }
        public string miejscowosc { get; set; }
        public string telefon { get; set; }
        public string email { get; set; }
        public int stanowiskoID { get; set; }
        public System.DateTime dataZatrudnienia { get; set; }
        public Nullable<System.DateTime> dataZwolnienia { get; set; }
    
        public virtual ICollection<Kurs> Kurs { get; set; }
        public virtual Stanowisko Stanowisko { get; set; }
        public virtual ICollection<Rozliczenie> Rozliczenie { get; set; }
    }
}
