//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgSchool.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rozliczenie
    {
        public int rozliczenieID { get; set; }
        public string numerRozliczenia { get; set; }
        public string dataRozliczenia { get; set; }
        public int pracownikID { get; set; }
        public int kursID { get; set; }
        public int iloscGodzin { get; set; }
        public decimal stawka { get; set; }
        public int bonusID { get; set; }
    
        public virtual Bonusy Bonusy { get; set; }
        public virtual Kurs Kurs { get; set; }
        public virtual Pracownik Pracownik { get; set; }
    }
}
