//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgSchool.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stanowisko
    {
        public Stanowisko()
        {
            this.Pracownik = new HashSet<Pracownik>();
        }
    
        public int stanowiskoID { get; set; }
        public string nazwaStanowiska { get; set; }
    
        public virtual ICollection<Pracownik> Pracownik { get; set; }
    }
}
