//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgSchool.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Firma = new HashSet<Firma>();
            this.Uczen = new HashSet<Uczen>();
        }
    
        public int statusID { get; set; }
        public string nazwa { get; set; }
        public string opis { get; set; }
    
        public virtual ICollection<Firma> Firma { get; set; }
        public virtual ICollection<Uczen> Uczen { get; set; }
    }
}
