//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgSchool.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypyMaterialow
    {
        public TypyMaterialow()
        {
            this.Materialy = new HashSet<Materialy>();
        }
    
        public int typID { get; set; }
        public string nazwa { get; set; }
    
        public virtual ICollection<Materialy> Materialy { get; set; }
    }
}
