//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgSchool.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TytulWplaty
    {
        public int tytulWplatyID { get; set; }
        public int wplataID { get; set; }
        public int kursID { get; set; }
        public decimal cena { get; set; }
        public int iloscGodzin { get; set; }
    
        public virtual Kurs Kurs { get; set; }
        public virtual Wplata Wplata { get; set; }
    }
}
