//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgSchool.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uczen
    {
        public Uczen()
        {
            this.Grupa = new HashSet<Grupa>();
            this.ListaDoGrup = new HashSet<ListaDoGrup>();
            this.OcenyUcznia = new HashSet<OcenyUcznia>();
            this.Wplata = new HashSet<Wplata>();
        }
    
        public int uczenID { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public System.DateTime dataUrodzenia { get; set; }
        public string pesel { get; set; }
        public string telefon { get; set; }
        public string telefonOpiekuna { get; set; }
        public string email { get; set; }
        public int statusID { get; set; }
        public Nullable<int> grupaID { get; set; }
        public Nullable<int> ocenaID { get; set; }
    
        public virtual ICollection<Grupa> Grupa { get; set; }
        public virtual ICollection<ListaDoGrup> ListaDoGrup { get; set; }
        public virtual Ocena Ocena { get; set; }
        public virtual ICollection<OcenyUcznia> OcenyUcznia { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<Wplata> Wplata { get; set; }
    }
}
