//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgSchool.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wplata
    {
        public Wplata()
        {
            this.TytulWplaty = new HashSet<TytulWplaty>();
        }
    
        public int wplataID { get; set; }
        public string numerWplaty { get; set; }
        public Nullable<int> uczenID { get; set; }
        public Nullable<int> firmaID { get; set; }
        public System.DateTime data { get; set; }
        public int rodzajPlatnosciID { get; set; }
    
        public virtual Firma Firma { get; set; }
        public virtual RodzajPlatnosci RodzajPlatnosci { get; set; }
        public virtual ICollection<TytulWplaty> TytulWplaty { get; set; }
        public virtual Uczen Uczen { get; set; }
    }
}
